info:
  author: vinay
  version: 1.0  
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
